---
#Checking Mariadb or Mysql is already Installed.
- name: Check if MySQL/Mariadb is already installed.
  stat: path=/etc/init.d/mysql
  register: mariadb_installed

- name: Error if Mysql/Mariadb is already installed.
  fail: msg="Oops !!! mysql or mariadb is already installed, Remove it first."
  when: mariadb_installed_stat_exist == true

- name: Adding Repository for mariadb
  include: repo.yml
  when: mariadb_installed.stat.exists == false

- name: Ensure Mariadb packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: __mariadb_packages
  register: deb_mariadb_install_packages

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MariaDB is stopped after initial install.
  service: name=mysql state=stopped
  when: mariadb_installed.stat.exists == false

- name: Delete innodb log files created by apt package after initial install.
  shell: "rm -f {{ mariadb_datadir }}/ib_logfile[01]"
  when: mariadb_installed.stat.exists == false
